<?xml version="1.0" encoding="utf-8"?><Database Name="EyePatch" EntityNamespace="EyePatch.Core.Entity" ContextNamespace="EyePatch.Core.Entity" Class="EyePatchDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=MCKAY-DESKTOP\SQLEXPRESS;Initial Catalog=EyePatch;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="EyePatchConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Folder" Member="Folders">
    <Type Name="Folder">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ParentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Folder_Folder" Member="Folders" ThisKey="ID" OtherKey="ParentID" Type="Folder" />
      <Association Name="Folder_Page" Member="Pages" ThisKey="ID" OtherKey="FolderID" Type="Page" />
      <Association Name="Folder_Folder" Member="Parent" ThisKey="ParentID" OtherKey="ID" Type="Folder" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.WidgetInstance" Member="WidgetInstances">
    <Type Name="WidgetInstance">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="WidgetID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ContentAreaID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Contents" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Position" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Widget_WidgetInstance" Member="Widget" ThisKey="WidgetID" OtherKey="ID" Type="Widget" IsForeignKey="true" />
      <Association Name="ContentArea_WidgetInstance" Member="ContentArea" ThisKey="ContentAreaID" OtherKey="ID" Type="ContentArea" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Widget" Member="Widgets">
    <Type Name="Widget">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="GroupID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Widget_WidgetInstance" Member="WidgetInstances" ThisKey="ID" OtherKey="WidgetID" Type="WidgetInstance" />
      <Association Name="Plugin_Widget" Member="Plugin" ThisKey="GroupID" OtherKey="ID" Type="Plugin" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ContentArea" Member="ContentAreas">
    <Type Name="ContentArea">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PageID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="ContentArea_WidgetInstance" Member="WidgetInstances" ThisKey="ID" OtherKey="ContentAreaID" Type="WidgetInstance" />
      <Association Name="Page_ContentArea" Member="Page" ThisKey="PageID" OtherKey="ID" Type="Page" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Site" Member="Sites">
    <Type Name="Site">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Plugin" Member="Plugins">
    <Type Name="Plugin">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="Author" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="Plugin_Widget" Member="Widgets" ThisKey="ID" OtherKey="GroupID" Type="Widget" />
    </Type>
  </Table>
  <Table Name="dbo.Template" Member="Templates">
    <Type Name="Template">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ViewPath" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Controller" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Action" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="IsDefault" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AnalyticsKey" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Language" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Author" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Charset" Type="System.String" DbType="NVarChar(13)" CanBeNull="true" />
      <Column Name="Copyright" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(155)" CanBeNull="true" />
      <Column Name="Keywords" Type="System.String" DbType="NVarChar(874)" CanBeNull="true" />
      <Column Name="Robots" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="OgType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OgEmail" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OgPhone" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="OgImage" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="OgLongitude" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="OgLatitude" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="OgStreetAddress" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="OgLocality" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OgRegion" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OgCountry" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OgPostcode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Template_Page" Member="Pages" ThisKey="ID" OtherKey="TemplateID" Type="Page" />
    </Type>
  </Table>
  <Table Name="dbo.MediaFiles" Member="MediaFiles">
    <Type Name="MediaFile">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Url" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="AltText" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="LastModified" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Page" Member="Pages">
    <Type Name="Page">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Url" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ChangeFrequency" Type="System.Nullable&lt;EyePatch.Core.Mvc.Sitemap.ChangeFrequency&gt;" DbType="Int" CanBeNull="true" />
      <Column Name="Priority" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="LastModified" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="TemplateID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FolderID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MenuOrder" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsLive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsInMenu" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsHidden" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsDynamic" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Language" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Author" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Charset" Type="System.String" DbType="NVarChar(13)" CanBeNull="true" />
      <Column Name="Copyright" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(155)" CanBeNull="true" />
      <Column Name="Keywords" Type="System.String" DbType="NVarChar(874)" CanBeNull="true" />
      <Column Name="Robots" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="OgType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OgEmail" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OgPhone" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="OgImage" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="OgLongitude" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="OgLatitude" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="OgStreetAddress" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="OgLocality" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OgRegion" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OgCountry" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OgPostcode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Page_ContentArea" Member="ContentAreas" ThisKey="ID" OtherKey="PageID" Type="ContentArea" />
      <Association Name="Folder_Page" Member="Folder" ThisKey="FolderID" OtherKey="ID" Type="Folder" IsForeignKey="true" />
      <Association Name="Template_Page" Member="Template" ThisKey="TemplateID" OtherKey="ID" Type="Template" IsForeignKey="true" />
    </Type>
  </Table>
</Database>