<?xml version="1.0" encoding="utf-8"?><Database Name="EyePatch" Class="EyePatchBlogDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=MCKAY-DESKTOP\SQLEXPRESS;Initial Catalog=EyePatch;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="EyePatchConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Tag" Member="Tags">
    <Type Name="Tag">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Tag" Member="Name" Storage="_Tag1" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Tag_PostTag" Member="PostTags" ThisKey="ID" OtherKey="TagId" Type="PostTag" />
    </Type>
  </Table>
  <Table Name="dbo.PostTags" Member="PostTags">
    <Type Name="PostTag">
      <Column Name="PostId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TagId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Tag_PostTag" Member="Tag" ThisKey="TagId" OtherKey="ID" Type="Tag" IsForeignKey="true" />
      <Association Name="Post_PostTag" Member="Post" ThisKey="PostId" OtherKey="ID" Type="Post" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.BlogInfo" Member="BlogInfos">
    <Type Name="BlogInfo">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ListPageID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PostPageID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Disqus" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Post" Member="Posts">
    <Type Name="Post">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Url" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Body" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="Published" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="LastModified" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Association Name="Post_PostTag" Member="PostTags" ThisKey="ID" OtherKey="PostId" Type="PostTag" />
    </Type>
  </Table>
</Database>